In [35]:
import numpy as np
import xgboost as xgb

import matplotlib.pyplot as plt
import seaborn as sns 


from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn import metrics as met
from imblearn.over_sampling import SMOTE

In [27]:
# loading
y = np.genfromtxt('./data/label.csv',delimiter=',')

X = np.genfromtxt('./data/features_deprment_encoded.csv',delimiter=',')


#splitting
x_train, x_val, y_train, y_val = train_test_split(X,
                                                 y,
                                                 test_size = .2,
                                                 random_state=12)

In [10]:
# resampling the traninging data to change the balnce the data
sm = SMOTE(random_state=12)
x_res, y_res = sm.fit_sample(x_train, y_train)

In [11]:
xgb_model = xgb.XGBClassifier().fit(x_res, y_res)

In [14]:
predictions = xgb_model.predict(x_val)
actuals = y_val
print(met.confusion_matrix(actuals, predictions))

[[2243   13]
 [  24  720]]


In [15]:
(2243+720)/(2243+24+720+13)

0.9876666666666667

In [22]:
xgb_model = xgb.XGBClassifier().fit(x_train, y_train)

In [28]:
predictions = xgb_model.predict(x_val)
actuals = y_val
print(met.confusion_matrix(actuals, predictions))

[[2246   10]
 [  24  720]]


In [33]:
kf = KFold(n_splits=5, shuffle=True, random_state=12)
for train_index, test_index in kf.split(X):
    xgb_model = xgb.XGBClassifier().fit(X[train_index], y[train_index])
    predictions = xgb_model.predict(X[test_index])
    actuals = y[test_index]
    print(met.confusion_matrix(actuals, predictions))

[[2246   10]
 [  24  720]]
[[2297   10]
 [  29  664]]
[[2305   10]
 [  19  666]]
[[2261   10]
 [  41  688]]
[[2266   13]
 [  30  690]]


In [36]:
clf = GridSearchCV(xgb_model,
                   {'max_depth': [2, 4, 6],
                    'n_estimators': [50, 100, 200]}, verbose=1)
clf.fit(X, y)
print(clf.best_score_)
print(clf.best_params_)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:   18.4s finished


0.989799555407358
{'max_depth': 6, 'n_estimators': 200}


In [2]:

tr = 'ADMINISTRATIVER MITARBEITER DES TECHNISCHEN DIREKTORS (CTO) UND HR-MANAGERS'
tr.title()

'Administrativer Mitarbeiter Des Technischen Direktors (Cto) Und Hr-Managers'